### ISSUE TITLE
VS2017 RC offline installation guide is broken

### ISSUE THREAD

**Issue by ArashPartow** [Microsoft/visualstudio-docs#7]
The following documentation is broken:

https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md

The steps as provided in the documentation do not result in a successful completion of operations.

Comments on the following page are not being addressed by MS support:

https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio#comments-container

Some questions to consider:

- If the offline download ever completes, how can one tell if they've downloaded all the necessary components?  

- How large can we expect the download to be? 1GB/5GB/10GB?

- Without an MD for each of the files and all the files as a batch, how can we know (or be sure) the files that were downloaded were actually the intended files?

- Why does the vs_enterprise.exe tool not support resume operations?

- Why is the only option that can be customized the language settings? what if I'm only interested in C++ and none of the other MS _'stuff'_ why must the entire thing be downloaded?

- What are these so-called "certificates" that are mentioned in the documentation?  Why are they not clearly defined?

- Most importantly: **WHY isn't there an ISO available for VS2017 from MSDN subscriptions?**  as this has been the case for the past 15+ years.

**Comment by timsneath** [comment]
Thanks for the feedback, Arash. There are some good suggestions here. As this is the RC release, we're not done yet - either with the setup experience or the documentation. 

A few quick comments to some of your specific questions :

- The download represents the full cache size of the requested components. This is of the order of 10GB.
- We compare every downloaded file against a signed manifest (downloaded via HTTPS) as part of the installation process.
- We hear the request for partial download of a layout cache, and it's on our backlog. There are a few intricacies: if I've got a partial download, should I be able to select other workloads that I didn't download? If so, how should we warn users that those workloads require online access? If not, how do we warn users that they are only seeing a subset of the available product? Solvable problems, but right now we're working on driving up reliability and improving error reporting.

Stay tuned - we'll be adding more features and addressing some of these items before we release. 

Thanks so much for your feedback, Tim Sneath | Visual Studio Team

**Comment by ArashPartow** [comment]
@timsneath Thank-you for the update on this issue. I'll definitely stay tuned for more updates.

That being said it's great that Microsoft is working hard on evolving and _improving_ their products, but I think we can all agree as astute and competent individuals, that until new options are functioning **correctly** and **adequately** and are not a source of concern or loss of productivity that the previous _"ways and methods"_ of doing business should be made continuously available.

**Comment by jminer** [comment]
I've tried posting a comment on that page with an error I got from the installer (running out of space because it is using the wrong drive), but my comment won't show up unless I'm logged in. I thought it might be blocked as spam because of a URL in the error message. So I removed it and tried posting a second time, but it still won't show up. Yet I see someone else's comment that was posted after mine. Is this expected?

**Comment by timsneath** [comment]
Hi @jminer - not sure what the issue is with your authentication. But for what it's worth, the best way to report product issues is through the Report a Problem icon in the top right hand corner of the installer. That automatically captures logs and relevant telemetry (where opted in) and routes the issue directly to the relevant engineering team. 

Comments on the docs are monitored by the docs team, but they don't often contain the necessary context. Thanks so much! Tim

**Comment by jminer** [comment]
I was doing the offline download from the command line, so I never saw the Report a Problem button. Now I went ahead and opened the installer to get to it. Thanks!

**Comment by ArashPartow** [comment]
@jminer Please refrain from hijacking issue threads.  If you do want to raise an issue, make sure to create a **New Issue** with the associated details.

**[more information](http://www.defmacro.org/2013/04/03/issue-etiquette.html)**

**Comment by timsneath** [comment]
@ArashPartow - to respond more fully to your remaining questions now that the public release is out:

> Why does the vs_enterprise.exe tool not support resume operations?

We do support resume with the `--layout` parameter. If you stop an layout (e.g. Ctrl+Break) during creation, you can resume by running the same command a second time, and we'll pick up from where you left off. 


> Why is the only option that can be customized the language settings? what if I'm only interested in C++ and none of the other MS 'stuff' why must the entire thing be downloaded?

We now support partial layout. See the updated documentation and in particular #65 for further examples. 


> What are these so-called "certificates" that are mentioned in the documentation? Why are they not clearly defined?

These are certificates that are used for validating the integrity of the downloaded files when you run in an offline mode. We compare the signatures of the packages against these Microsoft trusted certificates. Simply right-click them to install them. 


Thanks again for your feedback and for helping us improve Visual Studio!

**Comment by YuilTheLion** [comment]
And Mr. timsneath, while doing the setup with the `--layout` parameter, it was mentioned that the components failed to download.
Will those components get downloaded by the end of process?
I am currently trying to download Visual Studio Enterprise 2017. **(not the RC release)**

**Comment by ghogen** [comment]
This issue is closed, so I will lock the comment thread here. For support and feedback please visit the available resources: 

Developer Community:
https://developercommunity.visualstudio.com/spaces/8/index.html

UserVoice:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide

MSDN forums:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/home

Or use product support.
https://www.visualstudio.com/vs/support/
